### ISSUE TITLE
Panic error when scanning RouteTable

### ISSUE THREAD

**Issue by joufflu1** [Azure/azqr#270]
Hi,

First of all, thanks for your tool !

## Actual Behavior

AZQR version : 2.02
Execution : Linux ( WSL2)

AZQR is crashing with this error when scanning route table on a subscription : 
The error was not occuring in version [v.2.0.0-preview.8] and is not occuring on all the subscriptions.

```
[Nov  5 13:11:02.803415] Retry: exit due to non-retriable status code
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfbe880]

goroutine 364 [running]:
github.com/Azure/azqr/internal/scanners/rt.(*RouteTableScanner).Scan(0xc0002dccc0, 0xc00054cf60)
        /home/runner/work/azqr/azqr/internal/scanners/rt/rt.go:46 +0x240
github.com/Azure/azqr/internal.Scanner.retry({}, 0x3, 0x0?, {0x1baf360, 0xc0002dccc0}, 0xc00054cf60)
        /home/runner/work/azqr/azqr/internal/scanner.go:237 +0x103
github.com/Azure/azqr/internal.Scanner.Scan.func1({0x1baf360?, 0xc0002dccc0?})
        /home/runner/work/azqr/azqr/internal/scanner.go:181 +0x5c
created by github.com/Azure/azqr/internal.Scanner.Scan in goroutine 1
        /home/runner/work/azqr/azqr/internal/scanner.go:180 +0xc87
```

## Steps to Reproduce the Problem

Scan Route table directly : 

azqr scan rt --debug -a=false -c=false -d=false -m=false --csv -s XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

Please find in attachment the debug output with hidden subscription :  [Debug_rt.txt](https://github.com/user-attachments/files/17632493/Debug_rt.txt)

Thanks for your help,
Regards,
David

**Comment by cmendible** [comment]
@joufflu1 can you download and run a scan with the binary from here: https://github.com/Azure/azqr/actions/runs/11687084396 and check if it's fixed?

**Comment by joufflu1** [comment]
@cmendible 

Thanks for your fix and the explanation. I confirm that the scan finished well with your fixed binary : 

$ ./azqr scan rt -a=false -c=false -d=false -m=false --csv -s XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
2024-11-05T16:27:35+01:00 INF Scanning subscriptions for Microsoft.Network/routeTables
2024-11-05T16:27:40+01:00 INF Scanning subscriptions for Resources
2024-11-05T16:27:41+01:00 INF Scanning subscriptions for Diagnostic Settings
2024-11-05T16:27:46+01:00 INF Scanning subscriptions/...6ab3799 for Private Endpoints
2024-11-05T16:27:57+01:00 INF Scanning subscriptions/...6ab3799 for Public IPs
2024-11-05T16:27:57+01:00 INF Scanning subscriptions/...6ab3799 for Microsoft.Network/routeTables
2024-11-05T16:27:58+01:00 INF Scanning subscriptions for Resource Count per Subscription and Type
2024-11-05T16:27:59+01:00 INF Generating Report: azqr_action_plan_2024_11_05_T162733.xlsx
2024-11-05T16:27:59+01:00 INF Skipping Advisor. No data to render
2024-11-05T16:27:59+01:00 INF Skipping Defender. No data to render
2024-11-05T16:27:59+01:00 INF Skipping Costs. No data to render
2024-11-05T16:27:59+01:00 INF Generating Report: azqr_action_plan_2024_11_05_T162733.recommendations.csv
2024-11-05T16:27:59+01:00 INF Generating Report: azqr_action_plan_2024_11_05_T162733.impacted.csv
2024-11-05T16:27:59+01:00 INF Generating Report: azqr_action_plan_2024_11_05_T162733.resourceType.csv
2024-11-05T16:27:59+01:00 INF Generating Report: azqr_action_plan_2024_11_05_T162733.inventory.csv
2024-11-05T16:27:59+01:00 INF Generating Report: azqr_action_plan_2024_11_05_T162733.defender.csv
2024-11-05T16:27:59+01:00 INF Generating Report: azqr_action_plan_2024_11_05_T162733.advisor.csv
2024-11-05T16:27:59+01:00 INF Generating Report: azqr_action_plan_2024_11_05_T162733.costs.csv
2024-11-05T16:27:59+01:00 INF Scan completed.

As a remark, I did not tested it on all the subscription but I will launch it now.

**Comment by cmendible** [comment]
Let me know, I'm also waiting confirmation on #268 before pushing the release.

**Comment by joufflu1** [comment]
On my side, I confirm that all the subscriptions (about 200) have been scanned with success.

Thanks you very much for this quick fix !
